[package]
name = "egui_struct"
authors = ["PingPongun <pp.pp4@vp.pl>"]
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
egui_struct_macros = { path = "./macros/" }
egui = { version = "0.23" }

indexmap = { version = "2.0", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }

[features]
indexmap = ["dep:indexmap"]
default = ["i18n", "serde"]
i18n = ["egui_struct_macros/i18n"]
serde = ["dep:serde"]

[workspace]
members = ["demo"]
